
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.awt.image.FilteredImageSource;
import java.awt.image.ImageFilter;
import java.awt.image.ImageProducer;
import java.awt.image.RescaleOp;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.GrayFilter;
import javax.swing.JOptionPane;
import org.opencv.core.Mat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author u14298
 */


public class Tela extends javax.swing.JFrame {
   public boolean running = true;
   public BufferedImage fotinha;
   public String url1,url2,url3,url4,url5,urlDeleta;
   public MeuResultSet set = null;
   public MeuPreparedStatement bd;
   public DAOAluno tAlunos = null;
   public BufferedImage foto1,foto2,foto3,foto4,foto5;
    public static BufferedImage matToBufferedImage(Mat matrix) {  
     int cols = matrix.cols();  
     int rows = matrix.rows();  
     int elemSize = (int)matrix.elemSize();  
     byte[] data = new byte[cols * rows * elemSize];  
     int type;  
     matrix.get(0, 0, data);  
     switch (matrix.channels()) {  
       case 1:  
         type = BufferedImage.TYPE_BYTE_GRAY;  
         break;  
       case 3:  
         type = BufferedImage.TYPE_3BYTE_BGR;  
         // bgr to rgb  
         byte b;  
         for(int i=0; i<data.length; i=i+3) {  
           b = data[i];  
           data[i] = data[i+2];  
           data[i+2] = b;  
         }  
         break;  
       default:  
         return null;  
     }  
     BufferedImage image = new BufferedImage(cols, rows, type);  
     image.getRaster().setDataElements(0, 0, cols, rows, data);  
     return image;  
   }
    /**
     * Creates new form Tela
     */
    private class closeSystem extends WindowAdapter
    {
        public void windowClosing (WindowEvent e)
        {
            running = false;
            System.exit(0);
        }
    }
    public Tela() throws ClassNotFoundException, SQLException {
        initComponents();
        this.addWindowListener(new closeSystem());
        url1 = "";
        url2 = "";
        url3 = "";
        url4 = "";
        url5 = "";
        urlDeleta = "";
        bd = new MeuPreparedStatement(
                   //"com.microsoft.sqlserver.jdbc.SQLServerDriver",
                   //"jdbc:sqlserver://localhost:1433;databasename=TCC",
                   //"TCC", "123456");
        "com.microsoft.sqlserver.jdbc.SQLServerDriver",
                 "jdbc:sqlserver://regulus:1433;databasename=BDu14298",
               "BDu14298", "BDu14298");
        
    }
    public void setFeed(BufferedImage feed){
        Graphics2D g = (Graphics2D)feedCamera.getGraphics();
        g.drawImage(feed,null,0,0);
        g.dispose();
        g = (Graphics2D)feedCamera1.getGraphics();
        g.drawImage(feed,null,0,0);
        g.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNINH: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        feedCamera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        chkNormal = new javax.swing.JCheckBox();
        chk25 = new javax.swing.JCheckBox();
        chk50 = new javax.swing.JCheckBox();
        chk75 = new javax.swing.JCheckBox();
        chk100 = new javax.swing.JCheckBox();
        btnTiraFoto = new javax.swing.JButton();
        pnlFoto1 = new javax.swing.JPanel();
        pnlFoto2 = new javax.swing.JPanel();
        pnlFoto3 = new javax.swing.JPanel();
        pnlFoto4 = new javax.swing.JPanel();
        pnlFoto5 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chk101 = new javax.swing.JCheckBox();
        btnTiraFoto1 = new javax.swing.JButton();
        pnlFoto6 = new javax.swing.JPanel();
        pnlFoto7 = new javax.swing.JPanel();
        pnlFoto8 = new javax.swing.JPanel();
        pnlFoto9 = new javax.swing.JPanel();
        feedCamera1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        chkNormal1 = new javax.swing.JCheckBox();
        chk26 = new javax.swing.JCheckBox();
        chk51 = new javax.swing.JCheckBox();
        chk76 = new javax.swing.JCheckBox();
        pnlFoto10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtRA = new javax.swing.JTextField();
        txtBusca = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbNome = new javax.swing.JRadioButton();
        rbRA = new javax.swing.JRadioButton();
        cbResultado = new javax.swing.JComboBox();
        alterar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout feedCameraLayout = new javax.swing.GroupLayout(feedCamera);
        feedCamera.setLayout(feedCameraLayout);
        feedCameraLayout.setHorizontalGroup(
            feedCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        feedCameraLayout.setVerticalGroup(
            feedCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Nome");

        chkNormal.setText("Normal");

        chk25.setText("25%");

        chk50.setText("50%");

        chk75.setText("75%");

        chk100.setText("100%");

        btnTiraFoto.setText("Tirar Foto");
        btnTiraFoto.setEnabled(false);
        btnTiraFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiraFotoActionPerformed(evt);
            }
        });

        pnlFoto1.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto1Layout = new javax.swing.GroupLayout(pnlFoto1);
        pnlFoto1.setLayout(pnlFoto1Layout);
        pnlFoto1Layout.setHorizontalGroup(
            pnlFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto1Layout.setVerticalGroup(
            pnlFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto2.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto2Layout = new javax.swing.GroupLayout(pnlFoto2);
        pnlFoto2.setLayout(pnlFoto2Layout);
        pnlFoto2Layout.setHorizontalGroup(
            pnlFoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto2Layout.setVerticalGroup(
            pnlFoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto3.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto3Layout = new javax.swing.GroupLayout(pnlFoto3);
        pnlFoto3.setLayout(pnlFoto3Layout);
        pnlFoto3Layout.setHorizontalGroup(
            pnlFoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto3Layout.setVerticalGroup(
            pnlFoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto4.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto4Layout = new javax.swing.GroupLayout(pnlFoto4);
        pnlFoto4.setLayout(pnlFoto4Layout);
        pnlFoto4Layout.setHorizontalGroup(
            pnlFoto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto4Layout.setVerticalGroup(
            pnlFoto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto5.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto5Layout = new javax.swing.GroupLayout(pnlFoto5);
        pnlFoto5.setLayout(pnlFoto5Layout);
        pnlFoto5Layout.setHorizontalGroup(
            pnlFoto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto5Layout.setVerticalGroup(
            pnlFoto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(feedCamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(chk25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk75)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk100))
                            .addComponent(chkNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTiraFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                        .addComponent(pnlFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(feedCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkNormal)
                            .addComponent(chk25)
                            .addComponent(chk50)
                            .addComponent(chk75)
                            .addComponent(chk100))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTiraFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFoto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlFoto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlFoto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlFoto4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        chk101.setText("100%");

        btnTiraFoto1.setText("Tirar Foto");
        btnTiraFoto1.setEnabled(false);
        btnTiraFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiraFoto1ActionPerformed(evt);
            }
        });

        pnlFoto6.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto6Layout = new javax.swing.GroupLayout(pnlFoto6);
        pnlFoto6.setLayout(pnlFoto6Layout);
        pnlFoto6Layout.setHorizontalGroup(
            pnlFoto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto6Layout.setVerticalGroup(
            pnlFoto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto7.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto7Layout = new javax.swing.GroupLayout(pnlFoto7);
        pnlFoto7.setLayout(pnlFoto7Layout);
        pnlFoto7Layout.setHorizontalGroup(
            pnlFoto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto7Layout.setVerticalGroup(
            pnlFoto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto8.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto8Layout = new javax.swing.GroupLayout(pnlFoto8);
        pnlFoto8.setLayout(pnlFoto8Layout);
        pnlFoto8Layout.setHorizontalGroup(
            pnlFoto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto8Layout.setVerticalGroup(
            pnlFoto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        pnlFoto9.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto9Layout = new javax.swing.GroupLayout(pnlFoto9);
        pnlFoto9.setLayout(pnlFoto9Layout);
        pnlFoto9Layout.setHorizontalGroup(
            pnlFoto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto9Layout.setVerticalGroup(
            pnlFoto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout feedCamera1Layout = new javax.swing.GroupLayout(feedCamera1);
        feedCamera1.setLayout(feedCamera1Layout);
        feedCamera1Layout.setHorizontalGroup(
            feedCamera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        feedCamera1Layout.setVerticalGroup(
            feedCamera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("Nome");

        txtNome1.setEnabled(false);

        chkNormal1.setText("Normal");

        chk26.setText("25%");

        chk51.setText("50%");

        chk76.setText("75%");

        pnlFoto10.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout pnlFoto10Layout = new javax.swing.GroupLayout(pnlFoto10);
        pnlFoto10.setLayout(pnlFoto10Layout);
        pnlFoto10Layout.setHorizontalGroup(
            pnlFoto10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlFoto10Layout.setVerticalGroup(
            pnlFoto10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jLabel3.setText("RA");

        txtRA.setEnabled(false);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Pesquisa:");

        rbNome.setText("Nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        rbRA.setText("RA");
        rbRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRAActionPerformed(evt);
            }
        });

        cbResultado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbResultadoMouseClicked(evt);
            }
        });

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        deletar.setText("Deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pnlFoto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFoto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(feedCamera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtBusca)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(rbNome)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(rbRA)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(txtNome1)
                                            .addComponent(txtRA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(alterar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(deletar)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(btnTiraFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(chkNormal1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk101)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNome)
                            .addComponent(rbRA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar)
                        .addGap(11, 11, 11)
                        .addComponent(cbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alterar)
                            .addComponent(deletar))
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addComponent(feedCamera1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNormal1)
                    .addComponent(chk26)
                    .addComponent(chk51)
                    .addComponent(chk76)
                    .addComponent(chk101))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTiraFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFoto6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFoto7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFoto8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFoto9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFoto10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gestão", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       try {
           if(!txtNome.getText().equals("")
                   && !url1.equals("")
                   && !url2.equals("")
                   && !url3.equals("")
                   && !url4.equals("")
                   && !url5.equals("")){
                tAlunos = new DAOAluno(bd);
                String url0 = "'"+txtNome.getText()+"','"+url1+url2+url3+url4+url5+"'";
                tAlunos.insertAlunos(url0);
           }else{
               JOptionPane.showConfirmDialog(rootPane,"Dados em branco");
           }
       } catch (ClassNotFoundException ex) {
       } catch (SQLException ex) {
       } catch (Exception ex) {
       }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnTiraFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiraFotoActionPerformed
        //BufferedImage foto1,foto2,foto3,foto4,foto5;
        Image mage;
        if(chkNormal.isSelected()){
            foto1 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);
            RescaleOp rescaleOp = new RescaleOp(2.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto1, foto1);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto1.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto1.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto1.getGraphics();
            g.drawImage(foto1,null,0,0);
            g.dispose();
            try {
                ImageIO.write(foto1,"png", new File("G:\\DATABASE\\"+txtNome.getText()+"1.png"));
                url1 = "G:\\DATABASE\\"+txtNome.getText()+"1.png*";
            } catch (IOException ex) {
            }
        }
        if(chk25.isSelected()){
            foto2 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(3.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto2, foto2);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto2.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto2.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto2.getGraphics();
            g.drawImage(foto2,null,0,0);
            g.dispose();
            try {
                ImageIO.write(foto2,"png", new File("G:\\DATABASE\\"+txtNome.getText()+"2.png"));
                url2 = "G:\\DATABASE\\"+txtNome.getText()+"2.png*";
            } catch (IOException ex) {
            }
        }
        if(chk50.isSelected()){
            foto3 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(4.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto3, foto3);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto3.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto3.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto3.getGraphics();
            g.drawImage(foto3,null,0,0);
            g.dispose();
            try {
                ImageIO.write(foto3,"png", new File("G:\\DATABASE\\"+txtNome.getText()+"3.png"));
                url3 = "G:\\DATABASE\\"+txtNome.getText()+"3.png*";
            } catch (IOException ex) {
            }
        }
        if(chk75.isSelected()){
            foto4 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(5.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto4, foto4);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto4.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto4.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto4.getGraphics();
            g.drawImage(foto4,null,0,0);
            g.dispose();
            try {
                ImageIO.write(foto4,"png", new File("G:\\DATABASE\\"+txtNome.getText()+"4.png"));
                url4 = "G:\\DATABASE\\"+txtNome.getText()+"4.png*";
            } catch (IOException ex) {
            }
        }
        if(chk100.isSelected()){
            foto5 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(6.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto5, foto5);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto5.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto5.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto5.getGraphics();
            g.drawImage(foto5,null,0,0);
            g.dispose();
            try {
                ImageIO.write(foto5,"png", new File("G:\\DATABASE\\"+txtNome.getText()+"5.png"));
                url5 = "G:\\DATABASE\\"+txtNome.getText()+"5.png";
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnTiraFotoActionPerformed

    private void btnTiraFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiraFoto1ActionPerformed
        //BufferedImage foto1,foto2,foto3,foto4,foto5;
        Image mage;
        if(chkNormal1.isSelected()){
            foto1 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);
            RescaleOp rescaleOp = new RescaleOp(2.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto1, foto1);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto1.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto1.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto6.getGraphics();
            g.drawImage(foto1,null,0,0);
            g.dispose();
            url1 = "G:\\DATABASE\\"+txtNome1.getText()+"1.png";
        }
        if(chk26.isSelected()){
            foto2 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(3.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto2, foto2);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto2.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto2.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto7.getGraphics();
            g.drawImage(foto2,null,0,0);
            g.dispose();
            url2 = "G:\\DATABASE\\"+txtNome1.getText()+"2.png";
        }
        if(chk51.isSelected()){
            foto3 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(4.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto3, foto3);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto3.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto3.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto8.getGraphics();
            g.drawImage(foto3,null,0,0);
            g.dispose();
            url3 = "G:\\DATABASE\\"+txtNome1.getText()+"3.png";
        }
        if(chk76.isSelected()){
            foto4 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(5.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto4, foto4);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto4.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto4.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto9.getGraphics();
            g.drawImage(foto4,null,0,0);
            g.dispose();
            url4 = "G:\\DATABASE\\"+txtNome1.getText()+"4.png";
        }
        if(chk101.isSelected()){
            foto5 = new BufferedImage(fotinha.getColorModel(),fotinha.copyData(fotinha.getRaster().createCompatibleWritableRaster()),true,null);;
            RescaleOp rescaleOp = new RescaleOp(6.0f, -80.0f, null);//CLAREAR E MELHORAR CONTRASTE.1
            rescaleOp.filter(foto5, foto5);//.2
            ImageFilter filter = new GrayFilter(true, 50);  //.3
            ImageProducer producer = new FilteredImageSource(foto5.getSource(), filter);//.4
            Image mage2 = Toolkit.getDefaultToolkit().createImage(producer);//.5
            mage = mage2;//.6
            Graphics2D cv = (Graphics2D)foto5.createGraphics();//.7
            cv.drawImage(mage, 0,0,null);//.8
            cv.dispose();//.9
            Graphics2D g = (Graphics2D)pnlFoto10.getGraphics();
            g.drawImage(foto5,null,0,0);
            g.dispose();
            url5 = "G:\\DATABASE\\"+txtNome1.getText()+"5.png";
        }
    }//GEN-LAST:event_btnTiraFoto1ActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        if(!txtRA.getText().equals("")){
            if(chkNormal1.isSelected()){
                try {
                    ImageIO.write(foto1,"png", new File(url1));
                } catch (IOException ex) {
                }
            }
            if(chk26.isSelected()){
                try {
                    ImageIO.write(foto2,"png", new File(url2));
                } catch (IOException ex) {
                }
            }
            if(chk51.isSelected()){
                try {
                    ImageIO.write(foto3,"png", new File(url3));
                } catch (IOException ex) {
                }
            }
            if(chk76.isSelected()){
                try {
                    ImageIO.write(foto4,"png", new File(url4));
                } catch (IOException ex) {
                }
            }
            if(chk101.isSelected()){
                try {
                    ImageIO.write(foto5,"png", new File(url5));
                } catch (IOException ex) {
                }
            }
        }else{
            JOptionPane.showConfirmDialog(rootPane,"USUARIO NAO SELECIONADO");
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
       if(!txtBusca.getText().equals("")){
            try {
                tAlunos = new DAOAluno(bd);
            } catch (ClassNotFoundException ex) {
            } catch (SQLException ex) {
            } catch (Exception ex) {
            }
             if(rbNome.isSelected()){
                 try {
                     set = tAlunos.getAlunosBusca(txtBusca.getText(),true);
                 } catch (Exception ex) {
                 }
             }else{
                 try {
                     set = tAlunos.getAlunosBusca(txtBusca.getText(),false);
                 } catch (Exception ex) {
                 }
             }
             cbResultado.removeAllItems();
            try {
                while(set.resultado.next()){
                    cbResultado.addItem(set.resultado.getInt(1));
                }
            } catch (SQLException ex) {
            }
       }else{
           JOptionPane.showConfirmDialog(rootPane,"DADOS EM BRANCO");
       }
    }//GEN-LAST:event_buscarActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        if(rbNome.isSelected())
            rbRA.setSelected(false);
        else
            rbRA.setSelected(true);
    }//GEN-LAST:event_rbNomeActionPerformed

    private void cbResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbResultadoMouseClicked
       try {
                set = tAlunos.getAlunosBusca(cbResultado.getSelectedItem().toString(),false);
            } catch (Exception ex) {
            }
       try {
           set.resultado.next();
           txtRA.setText(String.valueOf(set.resultado.getInt(1)));
           txtNome1.setText(set.resultado.getString(2));
           urlDeleta = set.resultado.getString(3);
       } catch (SQLException ex) {
       }
    }//GEN-LAST:event_cbResultadoMouseClicked

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        if(!txtRA.getText().equals("")){
            try {
               StringTokenizer breaker = new StringTokenizer(urlDeleta,"*");
               while(breaker.hasMoreTokens()){
                   urlDeleta = breaker.nextToken();
                   File f = new File(urlDeleta);
                   f.delete();
               }
               tAlunos.deletaAluno(txtRA.getText());
           } catch (SQLException ex) {
           } catch (Exception ex) {
           }
       }
    }//GEN-LAST:event_deletarActionPerformed

    private void rbRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRAActionPerformed
        if(rbRA.isSelected())
            rbNome.setSelected(false);
        else
            rbNome.setSelected(true);
    }//GEN-LAST:event_rbRAActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela().setVisible(true);
                } catch (ClassNotFoundException ex) {
                } catch (SQLException ex) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton btnCadastrar;
    /*
    private javax.swing.JButton btnTiraFoto;
    */public javax.swing.JButton btnTiraFoto;
    /*
    private javax.swing.JButton btnTiraFoto1;
    */public javax.swing.JButton btnTiraFoto1;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox cbResultado;
    private javax.swing.JCheckBox chk100;
    private javax.swing.JCheckBox chk101;
    private javax.swing.JCheckBox chk25;
    private javax.swing.JCheckBox chk26;
    private javax.swing.JCheckBox chk50;
    private javax.swing.JCheckBox chk51;
    private javax.swing.JCheckBox chk75;
    private javax.swing.JCheckBox chk76;
    private javax.swing.JCheckBox chkNormal;
    private javax.swing.JCheckBox chkNormal1;
    private javax.swing.JButton deletar;
    private javax.swing.JPanel feedCamera;
    private javax.swing.JPanel feedCamera1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlFoto1;
    private javax.swing.JPanel pnlFoto10;
    private javax.swing.JPanel pnlFoto2;
    private javax.swing.JPanel pnlFoto3;
    private javax.swing.JPanel pnlFoto4;
    private javax.swing.JPanel pnlFoto5;
    private javax.swing.JPanel pnlFoto6;
    private javax.swing.JPanel pnlFoto7;
    private javax.swing.JPanel pnlFoto8;
    private javax.swing.JPanel pnlFoto9;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbRA;
    private javax.swing.JTextField txtBusca;
    /*
    private javax.swing.JTextField txtNome;
    */ public javax.swing.JTextField txtNome;
    /*
    private javax.swing.JTextField txtNome1;
    */public javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtRA;
    // End of variables declaration//GEN-END:variables
}
